### ISSUE TITLE
Add Process Tasks

### ISSUE THREAD

**Issue by nh758** [digi-serve/plugin_ABDesigner#23]
## Requirements
1. All process task can be added in a process:
    - [ ] Send Task
    - [ ] Sub Process Task
    - [ ] Service Task
        - [ ] Accounting: Process Batch 
        - [ ] Accounting: Fiscal Period Close
        - [ ] Accounting: Fiscal Year Close
        - [ ] Accounting: Journal Entry Archive
        - [ ] Query Task
        - [ ] Insert Record Task
        - [ ] Calculate Task
    - [ ] User Task
         - [ ] Approval Task

### Tasks
- [ ] Write Documentation

## Reference
User Task has placeholders for 'Confirm Off-Line Task' and  'Form Task' but not implemented in v1
